### ISSUE TITLE
questions about the dataset organization

### ISSUE THREAD

**Issue by ghost** [DeepPathology/MIDOG#3]
Hello, thanks for your contributions. I tried to reproduce your result in the paper. I have already downloaded the data from Google drive. May I ask you how to properly organize the dataset  in this project  or how to put the data under correct folder ? Thank you very much.

**Comment by Monk5088** [comment]
I also have the same problem while using the baseline folder, the drive folder seem to have different directory structure than the one used in code, could you please send the dataset link for the structure used in baseline folder python files.
Thanking in advance.

**Comment by maubreville** [comment]
Could you please indicate if your inquiry is about MIDOG 2022 or 2021? 

The baseline is not yet updated for MIDOG2022, we're working on that currently!

**Comment by FraukeWilm** [comment]
We have added the information about our directory structure with the inherent train/validation split. You can find it here: [train_val_split.txt](https://github.com/DeepPathology/MIDOG/blob/main/baseline/train_val_split.txt).

**Comment by Hamedamz** [comment]
Now that the 2021 challenge is over, is there any way to access MIDOG 2021 test dataset?

**Comment by Monk5088** [comment]
The inquiry is about midog 2021 challenge.
Also I am having problems with evaluation of object detection model with midog dataset, I have trained the model in in similar fashion as of the tutorial notebook of midog challenge, but I didn't find any support on fastai forum regarding Evaluation of obj det model.
I have used few codes such as https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/src/evaluators/coco_evaluator.py
 for finding various metrics but it doesn't seem to work with fastai code as it takes bbox classes which is not how bboxes are made in fastai v1 notebook showed in tutorial, 
Also I tried using the pascal.ipynb notebook in fastai dl3 course , but it takes pascal.json type annotation and the code doesn't work even after coco to pascal bbox conversion.
Could you please share some resources , notebooks which actually performed object detection evaluation of learner model of object_detection library of fastai , I have tried using icevision similar dataloading problem happens on same, 
Requesting your support on the same.
Thanking in advance ,
Warm regards,
Harshit

**Comment by FraukeWilm** [comment]
Dear Harshit,

please have a look at the implementation of the [official reference Docker](https://github.com/DeepPathology/MIDOG_reference_docker) for the MIDOG 2021 challenge. The [process.py](https://github.com/DeepPathology/MIDOG_reference_docker/blob/master/process.py) file imports and instanciates the model (MyMitosisDetection). It then loads all images that are part of the test set and processes each of them (using the process_image() method). As post-processing, it will also perform a final non-maxima suppression on the image, before creating the return dictionary which contains all individual detected points, which are ultimately stored in the file /output/mitotic-figures.json. You can then compute F1 scores using the detected and the ground truth bounding boxes or compute precision-recall curves if you export the detection score as well. 

Kind regards,
Frauke

**Comment by FraukeWilm** [comment]
@Hamedamz To allow the comparability of post-challenge results, we do not plan to publish the MIDOG 2021 test images, which could potentially lead to overfitting on the test dataset. However, we are currently working on a solution that enables developers to evaluate their algorithms on the test data without granting direct access the images (similar to the evaluation during the challenge). We will post an update on the MIDOG website once this solution is available.

**Comment by Monk5088** [comment]
Just today the notebook 101 stopped working I'm using a forked version of same notebook and I tried using the databunch from list it throw this error:
RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/fastai/data_block.py in _check_kwargs(ds, tfms, **kwargs)
    597         x = ds[0]
--> 598         try: x.apply_tfms(tfms, **kwargs)
    599         except Exception as e:

20 frames
RuntimeError: This function was deprecated since version 1.9 and is now removed. Please use the `torch.linalg.solve` function instead.

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/fastai/data_block.py in _check_kwargs(ds, tfms, **kwargs)
    598         try: x.apply_tfms(tfms, **kwargs)
    599         except Exception as e:
--> 600             raise Exception(f"It's not possible to apply those transforms to your dataset:\n {e}")
    601 
    602 class LabelList(Dataset):

Exception: It's not possible to apply those transforms to your dataset:
 This function was deprecated since version 1.9 and is now removed. Please use the `torch.linalg.solve` function instead.
This is the code in the notebook where it runs into error.
```lls = item_list.label_from_func(lambda x: x.y, label_cls=SlideObjectCategoryList)
lls = lls.transform(tfms, tfm_y=True, size=patch_size)
```
Can you please share a notebook using latest version of fastai which uses object_detection library of fastai and is able to load the dataset of midog?
Thanking you 
![Screenshot (64)](https://user-images.githubusercontent.com/52120096/178688863-7655e83e-0485-4416-a388-502e1f864157.png)

**Comment by Monk5088** [comment]
![Screenshot (65)](https://user-images.githubusercontent.com/52120096/178689012-70034b34-adb1-4135-b049-e530532fec56.png)
Using the notebook 101 itself also throws error , please update the notebook or please share a notebook which is going to be used as tutorial notebook for midog 2022 challenge.

**Comment by FraukeWilm** [comment]
Dear Harshit,

the [MIDOG_ObjectDetecton_101.ipynb](https://colab.research.google.com/drive/1uQNnpldgypSWX304QrVzvRjN5cKygn0B#scrollTo=NvOPXHfk2PzM) notebook was created for fastai **v1**. As fastai **v2** substantially changed data handling pipelines, it is not surprising that the provided code does not compile for fastai v2. We have tested the notebook this morning with fastai 1.0.61, which worked well. At the moment, we do not have the resources to adapt the code to fastai v2 but we are happy about anyone willing to contribute to the project and can merge proposed adaptations to the code into our GitHub.

Kind regards,
Frauke

**Comment by maubreville** [comment]
Sorry, this is all unrelated to the topic. This is also not the forum for asking for help with training an object detector. Closing this issue.

**Comment by Monk5088** [comment]
Can you send me pre run notebook of midog 101 which is ran today or yesterday, because I have tried it several times and it always gives error for dataloader part.
 Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kbreininger** [comment]
Hi Harshit,

We added compatible versions of pytorch and torchvision for the midog 101 notebook. It should now run smoothly on Google Colab.

Please note that this this issue is now closed, no further answers will be added here.

Regards,
Katharina

**Comment by Monk5088** [comment]
I ran the code after adding 
```
!pip install torch==1.5.0 torchvision==0.6.0
```
but now the learn.load('path/to/.pth file') is not working , can you please refer with the fastai team and get back with a permanent solution on how to use the library which you guys used for MIDOG challenge.
Learn.load gives this error:
AttributeError                            Traceback (most recent call last)
<ipython-input-42-bf70cd66d693> in <module>()
----> 1 learn=learn.load('/content/drive/MyDrive/
![Screenshot (67)](https://user-images.githubusercontent.com/52120096/179386373-5a42bf5d-bb04-429f-990c-cf2d79379109.png)
trained_model_bs64_GC',with_opt=True, strict=True)

2 frames
/usr/local/lib/python3.7/dist-packages/torch/serialization.py in __init__(self, name_or_buffer)
    244 class _open_zipfile_reader(_opener):
    245     def __init__(self, name_or_buffer):
--> 246         super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
    247 
    248 

AttributeError: 'PosixPath' object has no attribute 'tell'
