### ISSUE TITLE
Dataloader of the MIDOG 101 notebook not working due to change in some dependencies and/or libraries.

### ISSUE THREAD

**Issue by Monk5088** [DeepPathology/MIDOG#4]
I was trying to run the :[https://colab.research.google.com/drive/1uQNnpldgypSWX304QrVzvRjN5cKygn0B?usp=sharing](https://colab.research.google.com/drive/1uQNnpldgypSWX304QrVzvRjN5cKygn0B?usp=sharing#scrollTo=p1sTkpB79Zs8)[#](https://colab.research.google.com/drive/1uQNnpldgypSWX304QrVzvRjN5cKygn0B?usp=sharing#scrollTo=p1sTkpB79Zs8)[scrollTo=ilX5Df0j2PYf](https://colab.research.google.com/drive/1uQNnpldgypSWX304QrVzvRjN5cKygn0B?usp=sharing#scrollTo=ilX5Df0j2PYf) notebook provided in the MIDOG Website.
And the dataloader seems to not work when transformers are being used , it might be because of the old FASTAIv1 code used in the notebook .
This is the code where error occurs before databunch is called from labellists:
```
lls = lls.transform(tfms, tfm_y=True, size=patch_size)
data = lls.databunch(bs=batch_size, collate_fn=bb_pad_collate,num_workers=0).normalize()
```
ERROR:
RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/fastai/data_block.py](https://localhost:8080/#) in _check_kwargs(ds, tfms, **kwargs)
    597         x = ds[0]
--> 598         try: x.apply_tfms(tfms, **kwargs)
    599         except Exception as e:

20 frames
RuntimeError: This function was deprecated since version 1.9 and is now removed. Please use the `torch.linalg.solve` function instead.

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/fastai/data_block.py](https://localhost:8080/#) in _check_kwargs(ds, tfms, **kwargs)
    598         try: x.apply_tfms(tfms, **kwargs)
    599         except Exception as e:
--> 600             raise Exception(f"It's not possible to apply those transforms to your dataset:\n {e}")
    601 
    602 class LabelList(Dataset):

Exception: It's not possible to apply those transforms to your dataset:
 This function was deprecated since version 1.9 and is now removed. Please use the `torch.linalg.solve` function instead.

Could you please share a notebook that has updated code of fastai and doesn't run into runtime errors like the same?
Also if the MIDOG 2022 is not yet ready but has same format as MIDOG 2021 ,you could share tutorial notebook of the same if it is working fine.
Thanks for all the support,
Harshit
![Screenshot (65)](https://user-images.githubusercontent.com/52120096/178967384-5fe5825b-1844-4854-b457-2ee0e57488e8.png)

**Comment by Monk5088** [comment]
![Screenshot (65)](https://user-images.githubusercontent.com/52120096/178967281-4b24ce98-3df0-4088-ab6e-12b6a43a4a5b.png)

**Comment by kbreininger** [comment]
Dear Harshit,

We added compatible versions of pytorch and torchvision for the midog 101 notebook to work with fastAI v1. It should now run smoothly on Google Colab again.

If you require fastAI v2 support to implement _your_ approach, we can not support this request and kindly request you to do the corresponding adaptations needed to implement your method yourself. As mentioned already by Frauke, if you want to share these adaptations, we are happy to merge these adaptation into our github (see:  https://github.com/DeepPathology/MIDOG/issues/3#issuecomment-1182990824)

We currently do not plan to make a separate notebook available for MIDOG 2022, but will inform the community here and on the website if additional example code is provided.

Regards,
Katharina
